version: "3"
services:
  package:
    image: registry.gitlab.com/aplus-framework/images/package:2
    container_name: package-framework
    working_dir: /package
    volumes:
      - .:/package
    tty: true
  package-latest:
    image: registry.gitlab.com/aplus-framework/images/package:latest
    container_name: package-framework-last
    working_dir: /package
    volumes:
      - .:/package
    tty: true
